### ISSUE TITLE
What is this calculation based on?

### ISSUE THREAD

**Issue by webhat** [brooksware2000/Hobbybotics-AD595-Breakout#1]
Hi,

What is this calculation based on?
Is this in any way calibrated?

```
double AD595::tempC() {
  return (5.0 * analogRead(_DO) * 100.0) / 1024.0;
}
```

**Comment by brooksware2000** [comment]
In short, the AD595 outputs an analog value.  The below formula takes into account the precision of the 10-bit ADC built into the Arduino and converts the read voltage value to a corresponding temperature value.  The AD595 has built in calibration.

DO (signal pin from AD595) can be connected to any of the analog pins A0-A5.

DO outputs a voltage between 0 and 5V that correlates with the measured temperature.

The generated voltage on the analog pin is linear with temperature.  The AD595 outputs 10mV/C degree Celsius i.e. 1V = 100C, 2V = 200C…5V = 500C.  The maximum temperature with a voltage reference of 5V is 500C.

The 10-bit ADC in the ATmega328 chips maps the analog voltage (0 to 5V) to a corresponding integer value between 0 and 1023.

The conversion formula:

celsius = (5.0 * analogRead(pin) * 100.0) / 1024.0;
fahrenheit = (((celsius * 9) / 5) + 32);

converts the ADC value to its temperature equivalent in Celsius and Fahrenheit.

Hope this helps.  If not, let me know.

V/r

Curtis

**Comment by webhat** [comment]
Thanks for the reply, that helps enormously.

I had read that one should calibrate thermocouplings at 0ºc to ensure optimal accuracy, I assumed that it was something like that. This is a much better reason.
